const NANOIDLENGTH = 8;
const APPNAME = "letshost";
const APPURL = "http://localhost:5173";
const VERIFICATIONTOKENEXPIRYTIME = 1000 * 60 * 60 * 24 * 7;
const REDIS_EXP = 1000 * 60 * 60 * 24;
export {
  NANOIDLENGTH,
  APPNAME,
  APPURL,
  VERIFICATIONTOKENEXPIRYTIME,
  REDIS_EXP,
};
