receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        auth:
          authenticator: basicauth/server
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 1s
    send_batch_size: 512

exporters:
  otlphttp/loki:
    endpoint: ${LOKI_OTLP_ENDPOINT}

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  basicauth/server:
    htpasswd:
      inline: |
        ${OTEL_INGEST_HTPASSWD}

service:
  extensions: [health_check, basicauth/server]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
