const samplePrompts = [
  "A futuristic cityscape at sunset with flying cars",
  "A serene forest with glowing magical plants",
  "Portrait of a warrior princess in armor",
  "An astronaut exploring an alien planet with purple skies",
  "A cozy cabin in the snowy mountains at night",
  "A bustling cyberpunk street market",
  "A majestic dragon soaring above a medieval castle",
  "Underwater coral reef teeming with colorful fish",
  "A steampunk airship flying over Victorian London",
  "A whimsical fantasy village with mushroom houses",
  "A robot and a child sharing a moment in a park",
  "An ancient temple hidden in a jungle",
  "A close-up of a butterfly with iridescent wings",
  "A vintage train crossing a bridge over a canyon",
  "A surreal dreamscape with floating islands",
  "A samurai standing on a misty mountain peak",
  "A futuristic sports car racing through neon-lit streets",
  "A mystical forest with giant glowing mushrooms",
  "A portrait of an old wizard casting a spell",
  "A peaceful beach with bioluminescent waves at night",
  "A medieval knight riding a white horse",
  "A vibrant carnival with colorful tents and fireworks",
  "A cosmic scene with planets aligned in a row",
  "A cute robot pet playing in a backyard",
  "A surreal painting of clocks melting over trees",
  "A dramatic thunderstorm over a desert landscape",
  "A fairy sitting on a flower petal",
  "A sci-fi city with towering skyscrapers and holograms",
  "A calm lake reflecting autumn trees",
  "A fantasy dragon perched on a cliff during sunrise",
  "A close-up of a cat with glowing eyes",
  "A golden retriever running through a field of sunflowers",
  "A spaceship landing on a frozen tundra",
  "A fantasy warrior with glowing sword in a dark forest",
  "A lush garden with exotic flowers and butterflies",
  "A mystical crystal cave with sparkling formations",
  "A vintage robot repairing an old clock",
  "A panoramic view of a canyon at sunset",
  "A fantasy castle floating in the clouds",
  "A surreal portrait of a woman with galaxy skin",
  "A steampunk inventor’s workshop filled with gadgets",
  "A cozy library with a roaring fireplace",
  "A dragon curled around a treasure hoard",
  "A glowing jellyfish drifting in the deep sea",
  "A futuristic soldier in battle armor",
  "A vintage bicycle leaning against a tree in autumn",
  "A cybernetic owl perched on a neon sign",
  "A magical girl casting a spell in a moonlit garden",
  "A snowy owl flying over a winter forest",
  "A colorful hot air balloon festival",
  "A portrait of a samurai with cherry blossoms falling",
  "A neon-lit diner in a retro-futuristic city",
  "A surreal landscape with giant floating flowers",
  "A cute alien pet with big eyes",
  "A medieval blacksmith forging a sword",
  "A lush tropical waterfall with rainbow mist",
  "A fantasy warrior riding a giant wolf",
  "A glowing phoenix rising from ashes",
  "A city skyline with fireworks on New Year’s Eve",
  "A portrait of a girl with butterfly wings",
  "A vintage car driving along a coastal road",
  "A giant treehouse village in the jungle",
  "A mysterious hooded figure in a foggy street",
  "A colorful underwater city with mermaids",
  "A futuristic robot painter creating a masterpiece",
  "A snowy mountain peak under northern lights",
  "A fantasy elf with glowing tattoos",
  "A dragonfly hovering over a pond at dawn",
  "A cyberpunk hacker in a dark room with monitors",
  "A peaceful Zen garden with koi fish",
  "A wizard’s tower with floating books and potions",
  "A forest path covered in golden autumn leaves",
  "A portrait of a woman with glowing cybernetic eyes",
  "A surreal scene with giant clock towers in the desert",
  "A cozy café on a rainy day with warm lighting",
  "A samurai helmet resting on a rock",
  "A glowing tree in a dark enchanted forest",
  "A futuristic motorcycle speeding on a neon highway",
  "A fantasy castle built inside a giant tree",
  "A portrait of a fox wearing a crown",
  "A spaceship flying through a colorful nebula",
  "A peaceful meadow with wildflowers and butterflies",
  "A glowing crystal ball on an ancient altar",
  "A cute robot baking cookies in a kitchen",
  "A dramatic sunset over a volcanic landscape",
  "A magical portal opening in a forest",
  "A surreal portrait of a woman with flowers growing from her hair",
  "A giant mechanical spider in a steampunk city",
  "A glowing lantern floating over a calm lake",
  "A cyberpunk street scene with neon signs and rain",
  "A medieval knight in shining armor on horseback",
  "A fantasy dragon resting on a mountaintop",
  "A futuristic city with flying trains",
  "A close-up of a wolf howling at the moon",
  "A glowing fairy ring in a meadow",
  "A portrait of an astronaut holding a glowing orb",
  "A peaceful beach with palm trees at sunset",
  "A surreal scene with floating geometric shapes",
  "A cute cat wearing steampunk goggles",
  "A vibrant coral reef with tropical fish",
  "A fantasy warrior woman with a glowing sword",
  "A steampunk airship flying over a cityscape",
  "A glowing jellyfish floating in space",
  "A forest clearing with ancient stone ruins",
  "A portrait of a dragon with fiery eyes",
  "A futuristic robot playing a grand piano",
  "A calm river flowing through a misty forest",
  "A glowing phoenix flying over a mountain",
  "A neon-lit alley in a cyberpunk city",
  "A fantasy elf archer aiming at a target",
  "A surreal landscape with giant mushrooms",
  "A cute alien creature holding a flower",
  "A medieval castle under a starry sky",
  "A glowing crystal cave with reflections",
  "A portrait of a warrior with glowing tattoos",
  "A peaceful garden with cherry blossoms",
  "A futuristic motorcycle speeding on a highway",
  "A dragon perched on a tower at sunset",
  "A glowing butterfly resting on a leaf",
  "A cozy cabin in the woods with smoke from chimney",
  "A surreal scene with floating islands and waterfalls",
  "A cyberpunk hacker with neon-lit glasses",
  "A magical girl flying over a cityscape",
  "A snowy owl perched on a tree branch",
  "A vibrant hot air balloon floating over mountains",
  "A portrait of a samurai in traditional armor",
  "A neon-lit diner on a rainy night",
  "A surreal landscape with giant flowers",
  "A cute alien pet with big eyes and antennae",
  "A medieval blacksmith working at a forge",
  "A tropical waterfall surrounded by lush plants",
  "A fantasy warrior riding a giant wolf",
  "A glowing phoenix rising from ashes",
  "A city skyline with fireworks",
  "A portrait of a girl with butterfly wings",
  "A vintage car on a coastal road",
  "A giant treehouse village",
  "A mysterious figure in a foggy street",
  "A colorful underwater city",
  "A futuristic robot painter",
  "A snowy mountain under northern lights",
  "A fantasy elf with glowing tattoos",
  "A dragonfly over a pond at dawn",
  "A cyberpunk hacker in a dark room",
  "A peaceful Zen garden",
  "A wizard’s tower with floating books",
  "A forest path with golden leaves",
  "A woman with glowing cyber eyes",
  "A surreal desert with clock towers",
  "A cozy café on a rainy day",
  "A samurai helmet on a rock",
  "A glowing tree in enchanted forest",
  "A futuristic motorcycle on neon highway",
  "A castle inside a giant tree",
  "A fox wearing a crown",
  "A spaceship in a colorful nebula",
  "A peaceful meadow with wildflowers",
  "A glowing crystal ball on altar",
  "A robot baking cookies",
  "A sunset over volcanic landscape",
  "A magical portal in forest",
  "A woman with flowers in hair",
  "A mechanical spider in steampunk city",
  "A lantern floating over lake",
  "A cyberpunk street with rain",
  "A knight on horseback",
  "A dragon on mountaintop",
  "A city with flying trains",
  "A wolf howling at moon",
  "A fairy ring in meadow",
  "An astronaut holding glowing orb",
  "A beach at sunset",
  "A surreal floating shapes",
  "A cat with steampunk goggles",
  "A coral reef with fish",
  "A warrior woman with sword",
  "A steampunk airship over city",
  "A jellyfish floating in space",
  "A forest clearing with ruins",
  "A dragon with fiery eyes",
  "A robot playing piano",
  "A river in misty forest",
  "A phoenix flying over mountain",
  "A neon-lit cyberpunk alley",
  "An elf archer aiming",
  "A landscape with giant mushrooms",
  "An alien holding a flower",
  "A medieval castle under stars",
  "A crystal cave with reflections",
  "A warrior with glowing tattoos",
  "A garden with cherry blossoms",
  "A futuristic motorcycle on highway",
  "A dragon on tower at sunset",
  "A butterfly on a leaf",
  "A cabin with smoke chimney",
  "A floating islands with waterfalls",
  "A hacker with neon glasses",
  "A magical girl flying",
  "A snowy owl on branch",
  "A hot air balloon over mountains",
  "A samurai portrait",
  "A neon diner on rainy night",
  "A fantasy market filled with magical creatures",
  "An ancient library with floating books",
  "A glowing neon jellyfish in a dark ocean",
  "A cybernetic warrior in a post-apocalyptic wasteland",
  "A whimsical treehouse village in a giant oak",
  "A portrait of a queen with glowing eyes and jeweled crown",
  "A bioluminescent forest under a starry sky",
  "A dragon breathing ice instead of fire",
  "A futuristic city with transparent skyscrapers",
  "A vintage spaceship landing on Mars",
  "A floating island with a waterfall spilling into the clouds",
  "A giant robot protecting a small village",
  "A serene mountain lake with crystal clear water",
  "A close-up of a bee pollinating a flower",
  "A surreal underwater scene with floating clocks",
  "A warrior monk meditating in a bamboo forest",
  "A glowing tree with neon leaves in a dark forest",
  "A dragon wrapped around an ancient tower",
  "A futuristic train speeding through a desert",
  "A magical girl surrounded by floating lanterns",
  "A snowy owl with glowing feathers",
  "A cyberpunk cityscape reflected in rain puddles",
  "A portrait of an alien queen in regal attire",
  "A fantasy knight facing a giant spider",
  "A glowing crystal castle on an ice mountain",
  "A vintage car driving through a desert storm",
  "A steampunk inventor’s laboratory filled with gadgets",
  "A peaceful Zen garden with a koi pond",
  "A giant whale flying through a cloudy sky",
  "A robot and child exploring a lush jungle",
  "A portrait of a wolf with tribal markings",
  "A mystical cave glowing with purple crystals",
  "A cybernetic owl hunting at night",
  "A forest path covered in golden leaves in autumn",
  "A dragon flying through a fiery sky",
  "A futuristic city built on floating platforms",
  "A glowing jellyfish drifting through space",
  "A surreal painting of a woman with stars in her hair",
  "A medieval castle with glowing runes",
  "A cute alien creature with oversized eyes",
  "A warrior princess with a glowing sword",
  "A night market filled with colorful lanterns",
  "A close-up of a butterfly with stained glass wings",
  "A giant tree with a village built in its branches",
  "A glowing phoenix rising above a mountain",
  "A futuristic robot playing a violin",
  "A tropical beach with glowing bioluminescent waves",
  "A mysterious figure cloaked in mist",
  "A fantasy warrior riding a giant eagle",
  "A cyberpunk street vendor selling neon lights",
  "A peaceful garden with a small waterfall",
  "A glowing crystal ball surrounded by candles",
  "A portrait of a samurai with a neon sword",
  "A surreal landscape with floating islands and waterfalls",
  "A spaceship exploring a colorful nebula",
  "A dragon perched on a mountaintop at sunrise",
  "A vintage robot holding a bouquet of flowers",
  "A magical forest with glowing fairies",
  "A close-up of a cat with glowing green eyes",
  "A futuristic city skyline at night with flying cars",
  "A warrior monk standing under a cherry blossom tree",
  "A glowing jellyfish floating in a dark ocean",
  "A cyberpunk hacker typing on a holographic keyboard",
  "A portrait of a queen with a crown of stars",
  "A fantasy castle surrounded by a moat of lava",
  "A peaceful meadow with wildflowers and butterflies",
  "A glowing lantern floating over a calm lake",
  "A steampunk airship flying through the clouds",
  "A dragon breathing fire over a medieval village",
  "A futuristic motorcycle racing through neon streets",
  "A magical girl casting spells in a moonlit garden",
  "A snowy owl perched on a tree branch",
  "A portrait of a warrior with glowing tattoos",
  "A surreal landscape with giant mushrooms",
  "A cute alien pet playing with a ball of light",
  "A medieval knight in shining armor on horseback",
  "A glowing crystal cave filled with sparkling gems",
  "A cyberpunk city street with neon signs and rain",
  "A fantasy elf archer aiming at a target",
  "A peaceful Zen garden with koi fish swimming",
  "A dragon curled around a treasure hoard",
  "A vintage car driving down a coastal road",
  "A whimsical village with mushroom houses",
  "A glowing butterfly resting on a leaf",
  "A futuristic robot playing a grand piano",
  "A mystical forest with giant glowing mushrooms",
  "A portrait of a woman with glowing cybernetic eyes",
  "A steampunk inventor working in a cluttered workshop",
  "A close-up of a bee pollinating a flower",
  "A surreal painting of clocks melting over trees",
  "A glowing tree in an enchanted forest",
  "A cybernetic owl perched on a neon sign",
  "A magical girl flying over a cityscape",
  "A dragonfly hovering over a pond at dawn",
  "A peaceful beach with bioluminescent waves",
  "A medieval castle under a starry sky",
  "A glowing phoenix rising from ashes",
  "A vibrant carnival with colorful tents and fireworks",
  "A futuristic soldier in battle armor",
  "A robot and a child sharing a moment in a park",
  "A cozy cabin in the snowy mountains at night",
  "An astronaut exploring an alien planet with purple skies",
  "A samurai standing on a misty mountain peak",
  "A glowing jellyfish drifting in the deep sea",
  "A fantasy warrior woman with a glowing sword",
  "A giant mechanical spider in a steampunk city",
  "A glowing lantern floating over a calm lake",
  "A surreal portrait of a woman with flowers growing from her hair",
  "A cosmic scene with planets aligned in a row",
  "A futuristic city with flying trains",
  "A mystical crystal cave with sparkling formations",
  "A vintage robot repairing an old clock",
  "A peaceful garden with cherry blossoms",
  "A dragon perched on a tower at sunset",
  "A glowing butterfly resting on a leaf",
  "A close-up of a cat with glowing eyes",
  "A cyberpunk hacker in a dark room with monitors",
  "A glowing fairy ring in a meadow",
  "A fantasy elf with glowing tattoos",
  "A surreal landscape with floating geometric shapes",
  "A cute cat wearing steampunk goggles",
  "A magical portal opening in a forest",
  "A steampunk airship flying over Victorian London",
  "A forest path covered in golden autumn leaves",
  "A portrait of a fox wearing a crown",
  "A glowing crystal ball on an ancient altar",
  "A peaceful Zen garden with koi fish",
  "A futuristic motorcycle speeding on a neon highway",
  "A whimsical fantasy village with mushroom houses",
  "A vintage train crossing a bridge over a canyon",
  "A dragon breathing ice instead of fire",
  "A glowing neon jellyfish in a dark ocean",
  "A cybernetic warrior in a post-apocalyptic wasteland",
  "A floating island with a waterfall spilling into the clouds",
  "A giant robot protecting a small village",
  "A serene mountain lake with crystal clear water",
  "A surreal underwater scene with floating clocks",
  "A warrior monk meditating in a bamboo forest",
  "A glowing tree with neon leaves in a dark forest",
  "A futuristic train speeding through a desert",
  "A snowy owl with glowing feathers",
  "A cyberpunk cityscape reflected in rain puddles",
  "A portrait of an alien queen in regal attire",
  "A fantasy knight facing a giant spider",
  "A glowing crystal castle on an ice mountain",
  "A steampunk inventor’s laboratory filled with gadgets",
  "A giant whale flying through a cloudy sky",
  "A robot and child exploring a lush jungle",
  "A mystical cave glowing with purple crystals",
  "A dragon flying through a fiery sky",
  "A glowing jellyfish drifting through space",
  "A medieval castle with glowing runes",
  "A night market filled with colorful lanterns",
  "A portrait of a queen with glowing eyes and jeweled crown",
  "A bioluminescent forest under a starry sky",
  "A dragon wrapped around an ancient tower",
  "A magical girl surrounded by floating lanterns",
  "A futuristic city with transparent skyscrapers",
  "A floating island with a waterfall",
  "A glowing crystal ball surrounded by candles",
  "A dragon breathing fire over a medieval village",
  "A cyberpunk street vendor selling neon lights",
  "A glowing jellyfish floating in space",
  "A fantasy warrior riding a giant eagle",
  "A steampunk airship flying through the clouds",
  "A glowing phoenix flying over a mountain",
  "A portrait of a warrior with glowing tattoos",
  "A cute alien pet playing with a ball of light",
  "A magical forest with glowing fairies",
  "A futuristic robot playing a violin",
  "A snowy owl perched on a tree branch",
  "A vintage robot holding a bouquet of flowers",
  "A warrior monk standing under a cherry blossom tree",
  "A glowing jellyfish floating in a dark ocean",
  "A cyberpunk hacker typing on a holographic keyboard",
  "A fantasy castle surrounded by a moat of lava",
  "A glowing lantern floating over a calm lake",
  "A dragon curled around a treasure hoard",
  "A dragon perched on a mountaintop at sunrise",
  "A steampunk inventor working in a cluttered workshop",
  "A forest path with golden leaves",
  "A mystical forest with giant glowing mushrooms",
  "A futuristic city skyline at night with flying cars",
  "A glowing tree in an enchanted forest",
  "A portrait of a samurai with a neon sword",
  "A surreal landscape with floating islands and waterfalls",
  "A peaceful garden with cherry blossoms",
  "A warrior princess with a glowing sword",
  "A glowing butterfly resting on a leaf",
  "A dragonfly hovering over a pond at dawn",
  "A neon-lit diner on a rainy night",
  "A cute cat with glowing green eyes",
  "A magical girl casting spells in a moonlit garden",
  "A fantasy warrior woman with a glowing sword",
  "A glowing phoenix rising from ashes",
  "A serene forest with glowing magical plants",
  "A portrait of a warrior princess in armor",
  "An astronaut exploring an alien planet with purple skies",
  "A cozy cabin in the snowy mountains at night",
  "A bustling cyberpunk street market",
  "A majestic dragon soaring above a medieval castle",
  "Underwater coral reef teeming with colorful fish",
  "A steampunk airship flying over Victorian London",
  "A whimsical fantasy village with mushroom houses",
  "A robot and a child sharing a moment in a park",
  "An ancient temple hidden in a jungle",
  "A close-up of a butterfly with iridescent wings",
  "A vintage train crossing a bridge over a canyon",
  "A surreal dreamscape with floating islands",
  "A samurai standing on a misty mountain peak",
  "A futuristic sports car racing through neon-lit streets",
  "A mystical forest with giant glowing mushrooms",
  "A portrait of an old wizard casting a spell",
  "A peaceful beach with bioluminescent waves at night",
  "A medieval knight riding a white horse",
  "A vibrant carnival with colorful tents and fireworks",
  "A cosmic scene with planets aligned in a row",
  "A cute robot pet playing in a backyard",
  "A surreal painting of clocks melting over trees",
  "A dramatic thunderstorm over a desert landscape",
  "A fairy sitting on a flower petal",
  "A sci-fi city with towering skyscrapers and holograms",
  "A calm lake reflecting autumn trees",
  "A fantasy dragon perched on a cliff during sunrise",
  "A close-up of a cat with glowing eyes",
  "A golden retriever running through a field of sunflowers",
  "A spaceship landing on a frozen tundra",
  "A fantasy warrior with glowing sword in a dark forest",
  "A lush garden with exotic flowers and butterflies",
  "A mystical crystal cave with sparkling formations",
  "A vintage robot repairing an old clock",
  "A panoramic view of a canyon at sunset",
  "A fantasy castle floating in the clouds",
  "A surreal portrait of a woman with galaxy skin",
  "A steampunk inventor’s workshop filled with gadgets",
  "A cozy library with a roaring fireplace",
  "A dragon curled around a treasure hoard",
  "A glowing jellyfish drifting in the deep sea",
  "A futuristic soldier in battle armor",
  "A vintage bicycle leaning against a tree in autumn",
  "A cybernetic owl perched on a neon sign",
  "A magical girl casting a spell in a moonlit garden",
  "A snowy owl flying over a winter forest",
  "A colorful hot air balloon festival",
  "A portrait of a samurai with cherry blossoms falling",
  "A neon-lit diner in a retro-futuristic city",
  "A surreal landscape with giant floating flowers",
  "A cute alien pet with big eyes",
  "A medieval blacksmith forging a sword",
  "A lush tropical waterfall with rainbow mist",
  "A fantasy warrior riding a giant wolf",
  "A glowing phoenix rising from ashes",
  "A city skyline with fireworks on New Year’s Eve",
  "A portrait of a girl with butterfly wings",
  "A vintage car driving along a coastal road",
  "A giant treehouse village in the jungle",
  "A mysterious hooded figure in a foggy street",
  "A colorful underwater city with mermaids",
  "A futuristic robot painter creating a masterpiece",
  "A snowy mountain peak under northern lights",
  "A fantasy elf with glowing tattoos",
  "A dragonfly hovering over a pond at dawn",
  "A cyberpunk hacker in a dark room with monitors",
  "A peaceful Zen garden with koi fish",
  "A wizard’s tower with floating books and potions",
  "A forest path covered in golden autumn leaves",
  "A portrait of a woman with glowing cybernetic eyes",
  "A surreal scene with giant clock towers in the desert",
  "A cozy café on a rainy day with warm lighting",
  "A samurai helmet resting on a rock",
  "A glowing tree in a dark enchanted forest",
  "A futuristic motorcycle speeding on a neon highway",
  "A fantasy castle built inside a giant tree",
  "A portrait of a fox wearing a crown",
  "A spaceship flying through a colorful nebula",
  "A peaceful meadow with wildflowers and butterflies",
  "A glowing crystal ball on an ancient altar",
  "A cute robot baking cookies in a kitchen",
  "A dramatic sunset over a volcanic landscape",
  "A magical portal opening in a forest",
  "A surreal portrait of a woman with flowers growing from her hair",
  "A giant mechanical spider in a steampunk city",
  "A glowing lantern floating over a calm lake",
  "A cyberpunk street scene with neon signs and rain",
  "A medieval knight in shining armor on horseback",
  "A fantasy dragon resting on a mountaintop",
  "A futuristic city with flying trains",
  "A close-up of a wolf howling at the moon",
  "A glowing fairy ring in a meadow",
  "A portrait of an astronaut holding a glowing orb",
  "A peaceful beach with palm trees at sunset",
  "A surreal scene with floating geometric shapes",
  "A cute cat wearing steampunk goggles",
  "A vibrant coral reef with tropical fish",
  "A fantasy warrior woman with a glowing sword",
  "A steampunk airship flying over a cityscape",
  "A glowing jellyfish floating in space",
  "A forest clearing with ancient stone ruins",
  "A portrait of a dragon with fiery eyes",
  "A futuristic robot playing a grand piano",
  "A calm river flowing through a misty forest",
  "A glowing phoenix flying over a mountain",
  "A neon-lit alley in a cyberpunk city",
  "A fantasy elf archer aiming at a target",
  "A surreal landscape with giant mushrooms",
  "A cute alien creature holding a flower",
  "A medieval castle under a starry sky",
  "A glowing crystal cave with reflections",
  "A portrait of a warrior with glowing tattoos",
  "A peaceful garden with cherry blossoms",
  "A futuristic motorcycle speeding on a highway",
  "A dragon perched on a tower at sunset",
  "A glowing butterfly resting on a leaf",
  "A cozy cabin in the woods with smoke from chimney",
  "A surreal scene with floating islands and waterfalls",
  "A cyberpunk hacker with neon-lit glasses",
  "A magical girl flying over a cityscape",
  "A snowy owl perched on a tree branch",
  "A vibrant hot air balloon floating over mountains",
  "A portrait of a samurai in traditional armor",
  "A neon-lit diner on a rainy night",
  "A futuristic space station orbiting a distant planet",
  "A glowing neon dragon coiled around a skyscraper",
  "A serene Japanese garden in autumn with falling leaves",
  "A robotic bird soaring over a metallic city",
  "A fantasy mage casting spells in a crystal cavern",
  "A futuristic underwater city with glass domes",
  "A glowing alien artifact buried in a desert",
  "A surreal portrait of a man with clocks melting on his face",
  "A steam-powered mechanical elephant in a jungle",
  "A medieval banquet hall filled with knights and royalty",
  "A glowing crystal forest with bioluminescent plants",
  "A cyberpunk detective walking through rain-soaked streets",
  "A warrior princess riding a giant eagle",
  "A lush rainforest with colorful parrots and waterfalls",
  "A close-up of a dragon’s eye reflecting fire",
  "A futuristic soldier in powered armor on a battlefield",
  "A vibrant street market in a fantasy city",
  "A robot gardener tending glowing flowers",
  "A surreal underwater scene with floating whales",
  "A medieval castle siege under stormy skies",
  "A glowing phoenix soaring through a starry night",
  "A neon-lit arcade filled with retro video games",
  "A fantasy warrior wielding a flaming sword",
  "A quiet village covered in snow at twilight",
  "A portrait of a queen with a crown made of ice",
  "A floating island with a giant ancient tree",
  "A cybernetic samurai in a futuristic dojo",
  "A steam-powered airship battling dragons in the sky",
  "A mystical waterfall glowing with magical energy",
  "A surreal desert landscape with giant crystal shards",
  "A futuristic city park with robotic wildlife",
  "A fantasy elf queen sitting on a throne of vines",
  "A glowing jellyfish drifting through deep space",
  "A cozy witch’s cottage in a snowy forest",
  "A robotic cat curled up by a fireplace",
  "A portrait of a knight with a dragon-shaped shield",
  "A giant tree with doors and windows, home to forest spirits",
  "A cyberpunk street racer speeding through neon-lit tunnels",
  "A steampunk city with airships and clock towers",
  "A peaceful lake with floating lotus flowers at dawn",
  "A magical crystal growing from a mountain peak",
  "A futuristic robot DJ spinning tracks at a nightclub",
  "A dragon sleeping curled around a treasure trove",
  "A fantasy village with houses built into giant trees",
  "A glowing fairy dancing in a moonlit glade",
  "A portrait of an old wizard with glowing runes",
  "A surreal scene of giant fish swimming through the sky",
  "A cyberpunk hacker surrounded by digital data streams",
  "A medieval knight facing a fiery dragon",
  "A glowing alien temple on a distant planet",
  "A fantasy warrior wielding dual swords in battle",
  "A serene beach with glowing bioluminescent plankton",
  "A neon-lit nightclub with futuristic dancers",
  "A portrait of a girl with glowing tattoos",
  "A robotic arm crafting a delicate flower sculpture",
  "A lush valley with a winding river and ancient ruins",
  "A steampunk inventor testing a mechanical suit",
  "A futuristic motorbike racing through a desert canyon",
  "A magical forest with floating lanterns and fireflies",
  "A dragon flying over a city of glass towers",
  "A surreal portrait of a woman with stars in her eyes",
  "A cyberpunk street filled with holographic advertisements",
  "A glowing crystal floating above a mountain altar",
  "A fantasy castle built from ice and snow",
  "A robot warrior standing guard in a ruined temple",
  "A close-up of a wolf with glowing blue eyes",
  "A peaceful Zen garden with stone lanterns at night",
  "A portrait of a young mage holding a glowing staff",
  "A futuristic city with flying cars and floating gardens",
  "A glowing phoenix perched on a cliff at dawn",
  "A cozy cabin surrounded by glowing mushrooms",
  "A surreal scene of floating clocks in a desert",
  "A cybernetic bird perched on a neon sign",
  "A medieval blacksmith forging a glowing sword",
  "A fantasy elf riding a unicorn through a forest",
  "A glowing jellyfish illuminating a dark cave",
  "A robot exploring an abandoned city",
  "A portrait of a warrior woman with glowing armor",
  "A giant treehouse village with glowing windows",
  "A cyberpunk street vendor selling glowing gadgets",
  "A steampunk cityscape under a sunset sky",
  "A peaceful meadow filled with glowing fireflies",
  "A magical portal opening in an ancient stone circle",
  "A surreal landscape with floating crystal formations",
  "A futuristic robot painter creating glowing murals",
  "A dragonfly with wings made of stained glass",
  "A portrait of a samurai standing in a bamboo forest",
  "A neon-lit diner filled with futuristic robots",
  "A fantasy warrior wielding a sword made of light",
  "A glowing butterfly resting on a flower at night",
  "A cyberpunk hacker breaking into a digital vault",
  "A serene beach with glowing waves at sunset",
  "A surreal scene of floating islands with waterfalls",
  "A cozy library filled with glowing magical books",
  "A robot pet playing with a glowing ball",
  "A futuristic motorcycle speeding through neon streets",
  "A mystical forest with glowing ancient trees",
  "A portrait of a dragon with glowing scales",
  "A fantasy village illuminated by glowing lanterns",
  "A glowing crystal cave filled with magical creatures",
  "A cyberpunk street scene with rain and neon lights",
  "A medieval knight standing guard outside a castle",
  "A glowing phoenix rising over a snowy mountain",
  "A futuristic city skyline at dawn with flying vehicles",
  "A surreal portrait of a woman with flowers growing from her hair",
  "A robot crafting a delicate glass sculpture",
  "A dragon perched on a glowing mountain peak",
  "A magical girl casting a spell in a neon forest",
  "A cozy cabin with smoke rising in a snowy landscape",
  "A cybernetic owl flying through a neon-lit city",
  "A fantasy warrior woman wielding a glowing spear",
  "A glowing jellyfish drifting through a deep ocean trench",
  "A surreal landscape of floating clocks and gears",
  "A peaceful Zen garden with glowing lanterns at dusk",
  "A portrait of a wizard with a glowing staff",
  "A futuristic soldier in armor standing on a battlefield",
  "A glowing butterfly fluttering over a mystical pond",
  "A cyberpunk street filled with colorful graffiti",
  "A medieval castle surrounded by a glowing moat",
  "A fantasy dragon flying over a fiery volcano",
  "A robot exploring a glowing alien forest",
  "A surreal scene of floating geometric shapes in the sky",
  "A glowing crystal floating above a mystical altar",
  "A portrait of a knight with a glowing sword",
  "A peaceful meadow filled with glowing wildflowers",
  "A futuristic city park with robotic animals",
  "A glowing phoenix flying through a starry night",
  "A cozy cabin surrounded by glowing mushrooms",
  "A cyberpunk hacker working in a neon-lit room",
  "A fantasy warrior riding a glowing wolf",
  "A glowing jellyfish floating through space",
  "A surreal portrait of a woman with glowing tattoos",
  "A dragon curled around a glowing treasure chest",
  "A neon-lit alleyway in a futuristic city",
  "A medieval knight facing a glowing dragon",
  "A glowing crystal cave deep beneath a mountain",
  "A robot playing a glowing piano in a dark room",
  "A portrait of a mage with glowing eyes",
  "A futuristic motorcycle racing on glowing roads",
  "A glowing butterfly perched on a neon flower",
  "A fantasy village with glowing lanterns at night",
  "A cyberpunk street market filled with glowing gadgets",
  "A serene lake reflecting glowing autumn trees",
  "A magical girl flying over a glowing cityscape",
  "A glowing phoenix rising from glowing ashes",
  "A surreal landscape with glowing floating islands",
  "A portrait of a samurai with glowing armor",
  "A glowing jellyfish drifting through a mystical ocean",
  "A robot exploring glowing ancient ruins",
  "A peaceful garden filled with glowing flowers",
  "A cyberpunk street scene with glowing neon signs",
  "A fantasy warrior with glowing tattoos in a forest",
  "A glowing butterfly resting on a glowing leaf",
  "A medieval castle glowing under a starry sky",
  "A futuristic cityscape with glowing flying cars",
  "A surreal portrait of a woman with glowing hair",
  "A dragon flying over a glowing crystal mountain",
  "A glowing lantern floating above a calm river",
  "A robot pet playing with glowing toys in a park",
  "A glowing phoenix soaring through a glowing sky",
  "A cyberpunk hacker typing on a holographic keyboard",
  "A fantasy castle surrounded by a moat of lava",
  "A glowing lantern floating over a calm lake",
  "A dragon curled around a treasure hoard",
  "A dragon perched on a mountaintop at sunrise",
  "A steampunk inventor working in a cluttered workshop",
  "A forest path with golden leaves",
  "A mystical forest with giant glowing mushrooms",
  "A futuristic city skyline at night with flying cars",
  "A glowing tree in an enchanted forest",
  "A portrait of a samurai with a neon sword",
  "A surreal landscape with floating islands and waterfalls",
  "A peaceful garden with cherry blossoms",
  "A warrior princess with a glowing sword",
  "A glowing butterfly resting on a leaf",
  "A dragonfly hovering over a pond at dawn",
  "A neon-lit diner on a rainy night",
  "A cute cat with glowing green eyes",
  "A magical girl casting spells in a moonlit garden",
  "A fantasy warrior woman with a glowing sword",
  "A glowing phoenix rising from ashes",
  "A serene forest with glowing magical plants",
  "A portrait of a warrior princess in armor",
  "An astronaut exploring an alien planet with purple skies",
  "A cozy cabin in the snowy mountains at night",
  "A bustling cyberpunk street market",
  "A majestic dragon soaring above a medieval castle",
  "Underwater coral reef teeming with colorful fish",
  "A steampunk airship flying over Victorian London",
  "A whimsical fantasy village with mushroom houses",
  "A robot and a child sharing a moment in a park",
  "An ancient temple hidden in a jungle",
  "A close-up of a butterfly with iridescent wings",
  "A vintage train crossing a bridge over a canyon",
  "A surreal dreamscape with floating islands",
  "A samurai standing on a misty mountain peak",
  "A futuristic sports car racing through neon-lit streets",
  "A mystical forest with giant glowing mushrooms",
  "A portrait of an old wizard casting a spell",
  "A peaceful beach with bioluminescent waves at night",
  "A medieval knight riding a white horse",
  "A vibrant carnival with colorful tents and fireworks",
  "A cosmic scene with planets aligned in a row",
  "A cute robot pet playing in a backyard",
  "A surreal painting of clocks melting over trees",
  "A dramatic thunderstorm over a desert landscape",
  "A fairy sitting on a flower petal",
  "A sci-fi city with towering skyscrapers and holograms",
  "A calm lake reflecting autumn trees",
  "A fantasy dragon perched on a cliff during sunrise",
  "A close-up of a cat with glowing eyes",
  "A golden retriever running through a field of sunflowers",
  "A spaceship landing on a frozen tundra",
  "A fantasy warrior with glowing sword in a dark forest",
  "A lush garden with exotic flowers and butterflies",
  "A mystical crystal cave with sparkling formations",
  "A vintage robot repairing an old clock",
  "A panoramic view of a canyon at sunset",
  "A fantasy castle floating in the clouds",
  "A surreal portrait of a woman with galaxy skin",
  "A steampunk inventor’s workshop filled with gadgets",
  "A cozy library with a roaring fireplace",
  "A dragon curled around a treasure hoard",
  "A glowing jellyfish drifting in the deep sea",
  "A futuristic soldier in battle armor",
  "A vintage bicycle leaning against a tree in autumn",
  "A cybernetic owl perched on a neon sign",
  "A magical girl casting a spell in a moonlit garden",
  "A snowy owl flying over a winter forest",
  "A colorful hot air balloon festival",
  "A portrait of a samurai with cherry blossoms falling",
  "A neon-lit diner in a retro-futuristic city",
  "A surreal landscape with giant floating flowers",
  "A cute alien pet with big eyes",
  "A medieval blacksmith forging a sword",
  "A lush tropical waterfall with rainbow mist",
  "A fantasy warrior riding a giant wolf",
  "A glowing phoenix rising from ashes",
  "A city skyline with fireworks on New Year’s Eve",
  "A portrait of a girl with butterfly wings",
  "A vintage car driving along a coastal road",
  "A giant treehouse village in the jungle",
  "A mysterious hooded figure in a foggy street",
  "A colorful underwater city with mermaids",
  "A futuristic robot painter creating a masterpiece",
  "A snowy mountain peak under northern lights",
  "A fantasy elf with glowing tattoos",
  "A dragonfly hovering over a pond at dawn",
  "A cyberpunk hacker in a dark room with monitors",
  "A peaceful Zen garden with koi fish",
  "A wizard’s tower with floating books and potions",
  "A forest path covered in golden autumn leaves",
  "A portrait of a woman with glowing cybernetic eyes",
  "A surreal scene with giant clock towers in the desert",
  "A cozy café on a rainy day with warm lighting",
  "A samurai helmet resting on a rock",
  "A glowing tree in a dark enchanted forest",
  "A futuristic motorcycle speeding on a neon highway",
  "A fantasy castle built inside a giant tree",
  "A portrait of a fox wearing a crown",
  "A spaceship flying through a colorful nebula",
  "A peaceful meadow with wildflowers and butterflies",
  "A glowing crystal ball on an ancient altar",
  "A cute robot baking cookies in a kitchen",
  "A dramatic sunset over a volcanic landscape",
  "A magical portal opening in a forest",
  "A surreal portrait of a woman with flowers growing from her hair",
  "A giant mechanical spider in a steampunk city",
  "A glowing lantern floating over a calm lake",
  "A cyberpunk street scene with neon signs and rain",
  "A medieval knight in shining armor on horseback",
  "A fantasy dragon resting on a mountaintop",
  "A futuristic city with flying trains",
  "A close-up of a wolf howling at the moon",
  "A glowing fairy ring in a meadow",
  "A portrait of an astronaut holding a glowing orb",
  "A peaceful beach with palm trees at sunset",
  "A surreal scene with floating geometric shapes",
  "A cute cat wearing steampunk goggles",
  "A vibrant coral reef with tropical fish",
  "A fantasy warrior woman with a glowing sword",
  "A steampunk airship flying over a cityscape",
  "A glowing jellyfish floating in space",
  "A forest clearing with ancient stone ruins",
  "A portrait of a dragon with fiery eyes",
  "A futuristic robot playing a grand piano",
  "A calm river flowing through a misty forest",
  "A glowing phoenix flying over a mountain",
  "A neon-lit alley in a cyberpunk city",
  "A fantasy elf archer aiming at a target",
  "A surreal landscape with giant mushrooms",
  "A cute alien creature holding a flower",
  "A medieval castle under a starry sky",
  "A glowing crystal cave with reflections",
  "A portrait of a warrior with glowing tattoos",
  "A peaceful garden with cherry blossoms",
  "A futuristic motorcycle speeding on a highway",
  "A dragon perched on a tower at sunset",
  "A glowing butterfly resting on a leaf",
  "A cozy cabin in the woods with smoke from chimney",
  "A surreal scene with floating islands and waterfalls",
  "A cyberpunk hacker with neon-lit glasses",
  "A magical girl flying over a cityscape",
  "A snowy owl perched on a tree branch",
  "A vibrant hot air balloon floating over mountains",
  "A portrait of a samurai in traditional armor",
  "A neon-lit diner on a rainy night",
  "A glowing alien forest under a purple sky",
  "A majestic griffin perched on a mountain peak at dawn",
  "A mysterious ancient temple hidden in dense jungle",
  "A robotic dragon breathing streams of fire",
  "A futuristic city skyline reflected in calm water",
  "A fairy queen seated on a throne of flowers",
  "A cyberpunk street market bustling with neon signs",
  "A serene zen garden with glowing lanterns at night",
  "A giant octopus wrapping its tentacles around a sunken ship",
  "A surreal desert with floating, glowing cacti",
  "A magical library with books floating mid-air",
  "A knight in shining armor facing a massive ice dragon",
  "A bioluminescent cave filled with glowing bats",
  "A vintage car driving down a neon-lit city street",
  "A steampunk inventor working on a clockwork bird",
  "A cosmic whale swimming through stars and nebulae",
  "A glowing tree with roots that reach into the sky",
  "A dragonfly with metallic wings over a misty lake",
  "A floating island with a waterfall cascading into clouds",
  "A glowing phoenix perched on a branch of a cherry blossom tree",
  "A neon-lit nightclub with futuristic dancers",
  "A peaceful beach with glowing waves under a full moon",
  "A cybernetic panther prowling in a rain-soaked alley",
  "A castle floating above clouds with glowing spires",
  "A fairy tale cottage surrounded by glowing fireflies",
  "A warrior princess holding a sword made of light",
  "A vibrant coral reef glowing under bioluminescent light",
  "A robotic butterfly landing on a blooming flower",
  "A medieval market square alive with colorful stalls",
  "A glowing crystal floating in a dark forest clearing",
  "A futuristic spaceport bustling with alien ships",
  "A giant robot standing guard over a ruined city",
  "A surreal underwater palace made of glass",
  "A mystical forest with glowing mushrooms and faeries",
  "A cyberpunk hacker in a room filled with holographic screens",
  "A steampunk airship flying through stormy skies",
  "A glowing jellyfish drifting near underwater ruins",
  "A dragon soaring over an erupting volcano",
  "A fairy sitting on the petals of a giant glowing flower",
  "A glowing sword embedded in a rock on a mountaintop",
  "A serene mountain lake reflecting a glowing aurora",
  "A neon-lit street with futuristic vehicles speeding by",
  "A giant clockwork owl perched on a city rooftop",
  "A magical portal swirling with vibrant colors",
  "A knight riding a glowing horse through a dark forest",
  "A cybernetic mermaid swimming among neon coral reefs",
  "A floating city with glass domes and flying cars",
  "A dragon wrapped around a glowing crystal tower",
  "A portrait of an ancient wizard with glowing runes",
  "A glowing phoenix rising from a fiery nest",
  "A futuristic soldier in glowing armor standing on a battlefield",
  "A glowing butterfly fluttering over a calm pond",
  "A mystical treehouse village illuminated by lanterns",
  "A cyberpunk street artist painting glowing murals",
  "A surreal desert landscape with glowing sand dunes",
  "A glowing crystal cave with shimmering stalactites",
  "A fantasy warrior wielding a glowing spear",
  "A robot pet playing with glowing orbs in a dark room",
  "A glowing dragonfly hovering over a misty swamp",
  "A neon-lit cyberpunk marketplace at night",
  "A peaceful forest path lit by glowing lanterns",
  "A glowing jellyfish illuminating the ocean depths",
  "A dragon flying over glowing mountain peaks at sunrise",
  "A glowing swordfight between two armored knights",
  "A futuristic city glowing beneath a star-filled sky",
  "A giant mechanical dragon guarding a glowing fortress",
  "A glowing fairy dancing among cherry blossoms",
  "A robot crafting glowing jewelry in a workshop",
  "A glowing phoenix soaring above a snow-covered landscape",
  "A cyberpunk hacker breaking through glowing digital barriers",
  "A glowing crystal floating over a tranquil lake",
  "A fantasy village with glowing rooftops under the moonlight",
  "A glowing lantern floating over a calm river",
  "A neon-lit alleyway with rain reflecting colorful lights",
  "A glowing sword embedded in ancient ruins",
  "A mystical mage casting a glowing spell in a dark cave",
  "A glowing robotic owl perched on a branch at night",
  "A futuristic motorcycle speeding through glowing city streets",
  "A glowing butterfly resting on a robotic hand",
  "A dragon wrapped around a glowing magical tree",
  "A glowing phoenix rising from shimmering embers",
  "A cybernetic panther prowling through neon-lit ruins",
  "A peaceful garden filled with glowing flowers and fireflies",
  "A glowing crystal ball revealing a mystical vision",
  "A surreal scene of floating glowing islands over the ocean",
  "A glowing fairy sitting on a giant mushroom",
  "A robot painter creating glowing murals on city walls",
  "A glowing dragon perched on a glowing spire at twilight",
  "A knight standing on a glowing battlefield under a stormy sky",
  "A glowing jellyfish pulsing in a dark underwater cave",
  "A futuristic cityscape with glowing flying cars",
  "A glowing phoenix flying through a neon-lit sky",
  "A cyberpunk samurai wielding a glowing katana",
  "A glowing butterfly fluttering through a mystical forest",
  "A floating castle surrounded by swirling glowing clouds",
  "A glowing swordfight in a neon-lit arena",
  "A portrait of a mage with glowing magical tattoos",
  "A glowing crystal forest glowing under a full moon",
  "A futuristic soldier guarding a glowing city gate",
  "A glowing dragon breathing streams of icy fire",
  "A peaceful lake reflecting glowing autumn trees",
  "A glowing robotic fox running through a neon city",
  "A medieval castle glowing with enchanted light",
  "A glowing jellyfish illuminating sunken ruins",
  "A cyberpunk street filled with glowing neon advertisements",
  "A glowing fairy dancing under the stars",
  "A dragon soaring above glowing crystal cliffs",
  "A glowing sword embedded in a floating crystal",
  "A mystical portal swirling with glowing runes",
  "A glowing phoenix nestling in a glowing hollow tree",
  "A robot crafting glowing gadgets in a workshop",
  "A surreal landscape with glowing geometric shapes floating",
  "A glowing butterfly resting on a glowing lotus flower",
  "A cybernetic owl with glowing eyes flying at night",
  "A glowing warrior standing on a glowing mountain peak",
  "A fantasy village glowing softly under the moonlight",
  "A glowing crystal cave filled with sparkling gems",
  "A glowing dragonfly flying over a glowing river",
  "A futuristic city glowing under a glowing aurora",
  "A glowing lantern floating above a quiet village",
  "A glowing phoenix rising from glowing ashes",
  "A cyberpunk hacker glowing in a room filled with holograms",
  "A glowing treehouse village in an enchanted forest",
  "A dragon curled around a glowing treasure chest",
  "A glowing butterfly landing on a glowing robotic hand",
  "A glowing jellyfish drifting through glowing ocean waters",
  "A glowing swordfight between two glowing warriors",
  "A glowing castle surrounded by glowing mist",
  "A glowing robotic owl perched on a glowing streetlamp",
  "A glowing fairy flying through glowing moonlight",
  "A glowing warrior with glowing tattoos standing on a battlefield",
  "A glowing dragon perched on a glowing skyscraper at night",
  "A glowing butterfly fluttering through a glowing forest",
  "A glowing crystal floating over a glowing mountain",
  "A cyberpunk alley glowing with glowing neon lights",
  "A glowing phoenix soaring through glowing storm clouds",
  "A glowing jellyfish drifting through glowing currents",
  "A glowing sword embedded in glowing ancient stone",
  "A glowing phoenix rising over glowing crystal cliffs",
  "A glowing cyberpunk street glowing with glowing holograms",
  "A glowing medieval knight glowing under glowing stars",
  "A glowing futuristic city glowing under glowing aurora",
  "A glowing mystical portal glowing in glowing stone circle",
  "A glowing portrait of a glowing mage with glowing staff",
  "A glowing floating castle glowing amidst glowing clouds",
  "A glowing dragon curled around glowing treasure",
  "A glowing robot playing glowing piano",
  "A glowing girl surrounded by glowing butterflies",
  "A glowing lake surrounded by glowing mountains",
  "A glowing flower blooming under a glowing moon",
  "A glowing owl flying through a glowing forest",
  "A glowing sword shining in a dark cave",
  "A glowing castle on a floating island",
  "A glowing robot walking through a neon city",
  "A glowing phoenix flying over a glowing desert",
  "A glowing fairy sitting on a glowing mushroom",
  "A glowing dragon breathing fire in a dark sky",
  "A glowing butterfly resting on glowing leaves",
  "A glowing warrior standing on a glowing hill",
  "A glowing crystal shining in a dark forest",
  "A glowing mermaid swimming in glowing waters",
  "A glowing tree with glowing lanterns",
  "A glowing city under a glowing night sky",
  "A glowing dragonfly over glowing water",
  "A glowing sword glowing with magical power",
  "A glowing knight riding a glowing horse",
  "A glowing castle glowing in glowing mist",
  "A glowing owl perched on a glowing tree branch",
  "A glowing alien forest under a purple sky",
  "A majestic griffin perched on a mountain peak at dawn",
];
function shuffleArray() {
  const arr = samplePrompts.slice();
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

export function getRandomPrompts(n: number) {
  return shuffleArray().slice(0, n);
}
