const ApiRoutes = {
  register: "/users/register",
  login: "/users/login",
  generateNewTokens: "/users/generateNewTokens",
  oauth: "/users/oauth",
  googleLogin: "/users/auth/oauth/google/callback",
  githubLogin: "/users/auth/oauth/github/callback",
  spotifyLogin: "/users/auth/oauth/spotify/callback",
  facebookLogin: "/users/auth/oauth/facebook/callback",
  microsoftLogin: "/users/auth/oauth/microsoft/callback",
  forgotPassword: "/users/forgotPassword",

  //secured routes
  logout: "/users/logout",
  verify: "/users/verify",
  changePassword: "/users/changePassword",
  resendVerificationToken: "/users/resendVerificationToken",
  changeEmail: "/users/changeEmail",
  updateEmail: "/users/updateEmail",
  forgotUserName: "/users/forgotUserName",
  forgotEmail: "/users/forgotEmail",
  changeUserName: "/users/changeUserName",
  updateAvatar: "/users/updateAvatar",
  getUserDetails: "/users/getUserDetails",
  registerDomain: "/subdomains/register",
  updateDomain: "/subdomains/update",
  deleteDomain: "/subdomains/delete",
  changeContent: "/subdomains/changecontents",
  getUploadSignedUrl: "/subdomains/getuploadsignedurl",
  getContent: "/subdomains/getcontents",
  updateVisibility: "/subdomains/updatevisibility",
  getViewSignedUrl: "/subdomains/getviewsignedurl",
};
export default ApiRoutes;
